name: SnapIter

on:
  push:
    branches:
      - main

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install


  dockerbuild:
    needs: npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get commit count
        id: commitcount
        run: echo "count=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

      - name: Build the Docker image
        run: |
          VERSION=${{ steps.commitcount.outputs.count }}
          echo "Building version $VERSION"
          docker build \
            -t registry.bestanden.online/snapiter-frontend:latest \
            -t registry.bestanden.online/snapiter-frontend:$VERSION \
            -t rg.nl-ams.scw.cloud/snapiter/frontend:latest \
            -t rg.nl-ams.scw.cloud/snapiter/frontend:$VERSION .

      # - name: Docker login to Scaleway
      #   env:
      #     SCW_SECRET_KEY: ${{ secrets.scw_secret_key }}
      #   run: docker login -u nologin -p="$SCW_SECRET_KEY" rg.nl-ams.scw.cloud/snapiter
      # - name: Publish Docker image to Scaleway
      #   run: docker push rg.nl-ams.scw.cloud/snapiter/frontend:latest && docker push rg.nl-ams.scw.cloud/snapiter/frontend:$VERSION

      - name: Docker login to registry
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u registry -p="$DOCKER_PASSWORD" https://registry.bestanden.online

      - name: Publish dockerimage
        run: |
          VERSION=${{ steps.commitcount.outputs.count }}
          docker push registry.bestanden.online/snapiter-frontend:latest
          docker push registry.bestanden.online/snapiter-frontend:$VERSION
