name: SnapIter

on:
  push:
    branches:
      - main

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install

  dockerbuild:
    needs: npm
    runs-on: ubuntu-latest
    permissions:
      contents: read            # checkout
      packages: write           # needed to push to GHCR
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=ghcr.io/snapiter/snapiter:latest
          docker build -t "$IMAGE_TAG" .

      - name: Push Docker image
        run: |
          IMAGE_TAG=ghcr.io/snapiter/snapiter:latest
          docker push "$IMAGE_TAG"
